#!/bin/bash

# Colors:
RED='\033[0;31m'
REDBOLD='\033[0;31;1m'
GREENBOLD='\033[0;32;1m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
BWHITE='\033[1;37m'

# This script executes decac -p on all <example-name>.deca files in src/test/codegen/valid.
# The outputs are saved in files named <example-name>-p[-p].deca.
# Then checks that <example-name>-p.deca is exactly the same as <example-name>-p-p.deca (theorem 2)

# Change the current working directory to be in the project's directory
# wherever the script is executed from
cd "$(dirname "$0")"/../../../.. || exit 1

PATH=./src/test/script/launchers:"$PATH"

files=$(find ./src/test/deca/codegen/valid -maxdepth 1 -name "*.deca")


echo -e "${BWHITE}============================= -p option =============================\n"

for test in $files
do
    decac -p "$test" > "${test%.deca}"-p.deca
    decac -p "${test%.deca}"-p.deca > "${test%.deca}"-p-p.deca
    
    diff=$(diff "${test%.deca}"-p.deca "${test%.deca}"-p-p.deca)

    # check if passed
    if [ "$diff" = "" ] 
    then
        echo -e "${GREENBOLD}Test passed: $NOCOLOR${test/.\/src\/test\/deca\//} ${GREEN}decompiled twice gives the same result as the program decompiled once"
    else
        echo -e "${REDBOLD}Test failed: $NOCOLOR${test/.\/src\/test\/deca\//} ${RED}decompiled once and a second time does not give the same result"
        if [[ $1 == "--maven" ]];
        then
            exit 1
        fi
    fi
done

# Check readInt decompile
decac -p ./src/test/deca/codegen/interactive/readInt.deca > ./src/test/deca/codegen/interactive/readInt-p.deca
decac -p ./src/test/deca/codegen/interactive/readInt-p.deca > ./src/test/deca/codegen/interactive/readInt-p-p.deca

diff=$(diff ./src/test/deca/codegen/interactive/readInt-p.deca ./src/test/deca/codegen/interactive/readInt-p-p.deca)

# check if passed
if [ "$diff" = "" ] 
then
    echo -e "${GREENBOLD}Test passed: ${NOCOLOR}codegen/interactive/readInt.deca ${GREEN}decompiled twice gives the same result as the program decompiled once"
else
    echo -e "${REDBOLD}Test failed: ${NOCOLOR}codegen/interactive/readInt.deca ${RED}decompiled once and a second time does not give the same result"
    if [[ $1 == "--maven" ]];
    then
        exit 1
    fi
fi

# Check readFloat decompile
decac -p ./src/test/deca/codegen/interactive/readFloat.deca > ./src/test/deca/codegen/interactive/readFloat-p.deca
decac -p ./src/test/deca/codegen/interactive/readFloat-p.deca > ./src/test/deca/codegen/interactive/readFloat-p-p.deca

diff=$(diff ./src/test/deca/codegen/interactive/readFloat-p.deca ./src/test/deca/codegen/interactive/readFloat-p-p.deca)

# check if passed
if [ "$diff" = "" ] 
then
    echo -e "${GREENBOLD}Test passed: ${NOCOLOR}codegen/interactive/readFloat.deca ${GREEN}decompiled twice gives the same result as the program decompiled once"
else
    echo -e "${REDBOLD}Test failed: ${NOCOLOR}codegen/interactive/readFloat.deca ${RED}decompiled once and a second time does not give the same result"
    if [[ $1 == "--maven" ]];
    then
        exit 1
    fi
fi

decac -p -v > /dev/null 2> /dev/null

if [ "$?" -ne 0 ]
then
    echo -e "${GREENBOLD}Test passed:$GREEN decac -p -v returns an error"
else 
    echo -e "${REDBOLD}Test failed:$RED decac -p not implemented correctly"
    if [[ $1 == "--maven" ]];
    then
        exit 1
    fi
fi

# Cleaning process
rm ./src/test/deca/codegen/valid/*-p.deca;
rm ./src/test/deca/codegen/interactive/*-p.deca;
