#!/bin/bash

# Colors:
RED='\033[0;31m'
REDBOLD='\033[0;31;1m'
GREENBOLD='\033[0;32;1m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
BWHITE='\033[1;37m'


# Test the -d option by using decac on the same file but each 
# time adding a level of debug.
# Each time, the result is sent in a grep command to check
# The level of debug has changed.

# On se place dans le répertoire du projet (quel que soit le
# répertoire d'où est lancé le script) :
cd "$(dirname "$0")"/../../../../ || exit 1

PATH=./src/test/script/launchers:"$PATH"

echo -e "${BWHITE}\n============================= -d option =============================\n"

test="./src/test/deca/codegen/valid/provided/cond0.deca"

if decac $test | grep -q "."
then
    echo -e "${REDBOLD}Test failed:$RED decac -d not implemented correctly"
    if [[ $1 == "--maven" ]];
    then
        exit 1
    fi
else 
    echo -e "${GREENBOLD}Test passed:$GREEN decac does not show log info"
fi

if decac -d $test | grep -q "Application-wide trace level set to INFO"
then
    echo -e "${GREENBOLD}Test passed:$GREEN decac shows INFO info"
else 
    echo -e "${REDBOLD}Test failed:$RED decac -d not implemented correctly"
    if [[ $1 == "--maven" ]];
    then
        exit 1
    fi
fi

if decac -d -d $test | grep -q "Application-wide trace level set to DEBUG"
then
    echo -e "${GREENBOLD}Test passed:$GREEN decac shows DEBUG info"
else 
    echo -e "${REDBOLD}Test failed:$RED decac -d -d not implemented correctly"
    if [[ $1 == "--maven" ]];
    then
        exit 1
    fi
fi

if decac -d -d -d $test | grep -q "Application-wide trace level set to TRACE"
then 
    echo -e "${GREENBOLD}Test passed:$GREEN decac shows TRACE info"
else 
    echo -e "${REDBOLD}Test failed:$RED decac -d -d -d not implemented correctly"
    if [[ $1 == "--maven" ]];
    then
        exit 1
    fi
fi

if decac -d -d -d -d $test | grep -q "Application-wide trace level set to ALL"
then
    echo -e "${GREENBOLD}Test passed:$GREEN decac shows ALL info"
else 
    echo -e "${REDBOLD}Test failed:$RED decac -d -d -d -d not implemented correctly"
    if [[ $1 == "--maven" ]];
    then
        exit 1
    fi
fi

rm ./src/test/deca/codegen/valid/provided/cond0.ass