#!/bin/bash

# Colors:
RED='\033[0;31m'
REDBOLD='\033[0;31;1m'
GREENBOLD='\033[0;32;1m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
BWHITE='\033[1;37m'

# On se place dans le répertoire du projet (quel que soit le
# répertoire d'où est lancé le script) :
cd "$(dirname "$0")"/../../../.. || exit 1

echo -e "${BWHITE}\n============================= -b option =============================\n"

decac -b > ./src/test/script/options-scripts/option-b.tmp

if cat ./src/test/script/options-scripts/option-b.tmp | grep -q "."
then
    echo -e "$GREENBOLD Test passed: $GREEN Option -b successfully implemented\n"
else 
    echo -e "$REDBOLD Test failed: $RED Option -b not implemented\n"
    if [[ $1 == "--maven" ]];
    then
        exit 1
    fi
fi

rm ./src/test/script/options-scripts/option-b.tmp
