#!/bin/bash

# Colors:
RED='\033[0;31m'
REDBOLD='\033[0;31;1m'
GREENBOLD='\033[0;32;1m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
BWHITE='\033[1;37m'

# Test on different random aspects of the compiler.
# - Checks that decac command without file or option sends an error and the correct usage.
# - Checks that an error is returned when using decac on an unknown file
# - Checks that an error is returned when using decac on a not .deca file

# On se place dans le répertoire du projet (quel que soit le
# répertoire d'où est lancé le script) :
cd "$(dirname "$0")"/../../../../ || exit 1

PATH=./src/test/script/launchers:"$PATH"

echo -e "${BWHITE}\n============================= Other cases =============================\n"

if decac 2>&1 | grep -q "There is no file to compile"
then
    echo -e "${GREENBOLD}Test passed:$GREEN decac only returns an error and shows correct usage"
else 
    echo -e "${REDBOLD}Test failed:$RED decac without files or options does not show correct usage"
    if [[ $1 == "--maven" ]];
    then
        exit 1
    fi
fi

if decac "fileNotExisting.deca" 2>&1 | grep -q "Failed to open input file"
then
    echo -e "${GREENBOLD}Test passed:$GREEN decac on an unknown file shows an error"
else 
    echo -e "${REDBOLD}Test failed:$RED decac with an incorrect file name does not show an error"
    if [[ $1 == "--maven" ]];
    then
        exit 1
    fi
fi

if decac "notADecaFile.c" 2>&1 | grep -q "The file must be a .deca file."
then
    echo -e "${GREENBOLD}Test passed:$GREEN decac on a not .deca file shows an error"
else 
    echo -e "${REDBOLD}Test failed:$RED decac on a not .deca file does not show an error"
    if [[ $1 == "--maven" ]];
    then
        exit 1
    fi
fi

if decac -l 2>&1 | grep -q "Unknown option"
then
    echo -e "${GREENBOLD}Test passed:$GREEN decac with an unknown option returns an error"
else 
    echo -e "${REDBOLD}Test failed:$RED decac with an unknown option does not return an error"
    if [[ $1 == "--maven" ]];
    then
        exit 1
    fi
fi
